# Generated by Django 3.0.2 on 2021-10-04 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64)),
                ('content', models.CharField(blank=True, default='', max_length=256)),
                ('status', models.IntegerField(choices=[(0, '未完成'), (1, '完成')], default=0)),
                ('priority', models.IntegerField(choices=[(0, '优先级1'), (1, '优先级2'), (2, '优先级3'), (3, '优先级4')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
