# Generated by Django 3.0.2 on 2020-01-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64)),
                ('content', models.CharField(blank=True, default='', max_length=256)),
                ('status', models.IntegerField(choices=[(0, '未完成'), (1, '完成'), (2, '过期')], default=0)),
                ('priority', models.IntegerField(choices=[(0, '优先级1'), (1, '优先级2'), (2, '优先级3'), (3, '优先级4')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField()),
            ],
        ),
    ]
